
CXX		= $(CPPEXAMPLE_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(CPPEXAMPLE_LIBDIR)
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 -std=c++0x -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -shared
